export const cats = [
  {
    "id": 129,
    "label": "drehi-za-bremenni",
    "parentId": 207,
    "name": "Дрехи за бременни",
    "slug": "drehi-za-bremenni",
    "position": 21,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 21,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/drehi-za-bremenni/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 130,
    "label": "stoki-za-bliznatsi",
    "parentId": 139,
    "name": "Стоки за близнаци",
    "slug": "stoki-za-bliznatsi",
    "position": 7,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 7,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/stoki-za-bliznatsi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 132,
    "label": "stolcheta",
    "parentId": 195,
    "name": "Столчета",
    "slug": "stolcheta",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 2,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/stolcheta/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 134,
    "label": "vsichko-za-pochistvaneto",
    "parentId": 262,
    "name": "Всичко за почистването",
    "slug": "vsichko-za-pochistvaneto",
    "position": 10,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 10,
    "children": [],
    "path": "https://www.olx.bg/dom-i-gradina/vsichko-za-pochistvaneto/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 135,
    "label": "hrani-dobavki-napitki",
    "parentId": 262,
    "name": "Храни, добавки, напитки",
    "slug": "hrani-dobavki-napitki",
    "position": 12,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 12,
    "children": [],
    "path": "https://www.olx.bg/dom-i-gradina/hrani-dobavki-napitki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 137,
    "label": "drugi",
    "parentId": 262,
    "name": "Други",
    "slug": "drugi",
    "position": 14,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 14,
    "children": [],
    "path": "https://www.olx.bg/dom-i-gradina/drugi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 138,
    "label": "teniski",
    "parentId": 234,
    "name": "Тениски",
    "slug": "teniski",
    "position": 9,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 9,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/mzhki-drehi/teniski/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 139,
    "label": "za-bebeto-i-deteto",
    "parentId": 0,
    "name": "За бебето и детето",
    "slug": "za-bebeto-i-deteto",
    "position": 10,
    "viewType": "list",
    "iconName": "kids",
    "level": 1,
    "displayOrder": 10,
    "children": [
      130,
      140,
      150,
      173,
      178,
      185,
      195,
      1002
    ],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12,
    "img": "https://categories.olxcdn.com/assets/categories/olxbg/za-bebeto-i-deteto-139-1x.png"
  },
  {
    "id": 140,
    "label": "igrachki",
    "parentId": 139,
    "name": "Играчки",
    "slug": "igrachki",
    "position": 4,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 4,
    "children": [
      141,
      142,
      143,
      144,
      145,
      146,
      147,
      149
    ],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/igrachki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 141,
    "label": "detski-koli-velosipedi-trikolki",
    "parentId": 140,
    "name": "Детски коли, велосипеди, триколки",
    "slug": "detski-koli-velosipedi-trikolki",
    "position": 4,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 4,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/igrachki/detski-koli-velosipedi-trikolki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 142,
    "label": "gradinski-igrachki",
    "parentId": 140,
    "name": "Градински играчки",
    "slug": "gradinski-igrachki",
    "position": 7,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 7,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/igrachki/gradinski-igrachki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 143,
    "label": "koli-vlakcheta-radioupravlyaemi-igrachki",
    "parentId": 140,
    "name": "Коли, влакчета, радиоуправляеми играчки",
    "slug": "koli-vlakcheta-radioupravlyaemi-igrachki",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 1,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/igrachki/koli-vlakcheta-radioupravlyaemi-igrachki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 144,
    "label": "kukli-i-aksesoari",
    "parentId": 140,
    "name": "Кукли и аксесоари",
    "slug": "kukli-i-aksesoari",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 2,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/igrachki/kukli-i-aksesoari/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 145,
    "label": "plyusheni-igrachki",
    "parentId": 140,
    "name": "Плюшени играчки",
    "slug": "plyusheni-igrachki",
    "position": 3,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 3,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/igrachki/plyusheni-igrachki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 146,
    "label": "obrazovatelni-zanimatelni-igrachki",
    "parentId": 140,
    "name": "Образователни, занимателни играчки",
    "slug": "obrazovatelni-zanimatelni-igrachki",
    "position": 5,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 5,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/igrachki/obrazovatelni-zanimatelni-igrachki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 147,
    "label": "muzikalni-igrachki",
    "parentId": 140,
    "name": "Музикални играчки",
    "slug": "muzikalni-igrachki",
    "position": 6,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 6,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/igrachki/muzikalni-igrachki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 149,
    "label": "drugi",
    "parentId": 140,
    "name": "Други",
    "slug": "drugi",
    "position": 8,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 8,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/igrachki/drugi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 150,
    "label": "drehi",
    "parentId": 139,
    "name": "Дрехи",
    "slug": "drehi",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 1,
    "children": [
      151,
      152,
      153,
      155,
      156,
      157,
      158,
      159,
      160,
      161,
      162,
      164,
      165,
      166,
      167,
      168,
      169,
      170
    ],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 151,
    "label": "0-3-mesetsa-rst-do-62-sm",
    "parentId": 150,
    "name": "0-3 месеца (ръст до 62 см.)",
    "slug": "0-3-mesetsa-rst-do-62-sm",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 1,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/0-3-mesetsa-rst-do-62-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 152,
    "label": "3-6-mesetsa-rst-do-68-sm",
    "parentId": 150,
    "name": "3-6 месеца (ръст до 68 см.)",
    "slug": "3-6-mesetsa-rst-do-68-sm",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 2,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/3-6-mesetsa-rst-do-68-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 153,
    "label": "6-9-mesetsa-rst-do-74-sm",
    "parentId": 150,
    "name": "6-9 месеца (ръст до 74 см.)",
    "slug": "6-9-mesetsa-rst-do-74-sm",
    "position": 3,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 3,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/6-9-mesetsa-rst-do-74-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 155,
    "label": "9-12-mesetsa-rst-do-80-sm",
    "parentId": 150,
    "name": "9-12 месеца (ръст до 80 см.)",
    "slug": "9-12-mesetsa-rst-do-80-sm",
    "position": 5,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 5,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/9-12-mesetsa-rst-do-80-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 156,
    "label": "12-18-mesetsa-rst-do-86-sm",
    "parentId": 150,
    "name": "12-18 месеца (ръст до 86 см.)",
    "slug": "12-18-mesetsa-rst-do-86-sm",
    "position": 6,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 6,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/12-18-mesetsa-rst-do-86-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 157,
    "label": "18-24-mesetsa-rst-do-92-sm",
    "parentId": 150,
    "name": "18-24 месеца (ръст до 92 см.)",
    "slug": "18-24-mesetsa-rst-do-92-sm",
    "position": 7,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 7,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/18-24-mesetsa-rst-do-92-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 158,
    "label": "2-3-godini-rst-do-98-sm",
    "parentId": 150,
    "name": "2-3 години (ръст до 98 см.)",
    "slug": "2-3-godini-rst-do-98-sm",
    "position": 8,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 8,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/2-3-godini-rst-do-98-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 159,
    "label": "3-4-godini-rst-do-104-sm",
    "parentId": 150,
    "name": "3-4 години (ръст до 104 см.)",
    "slug": "3-4-godini-rst-do-104-sm",
    "position": 9,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 9,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/3-4-godini-rst-do-104-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 160,
    "label": "4-5-godini-rst-do-110-sm",
    "parentId": 150,
    "name": "4-5 години (ръст до 110 см.)",
    "slug": "4-5-godini-rst-do-110-sm",
    "position": 10,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 10,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/4-5-godini-rst-do-110-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 161,
    "label": "rst-do-116-sm",
    "parentId": 150,
    "name": "Ръст до 116 см.",
    "slug": "rst-do-116-sm",
    "position": 11,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 11,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/rst-do-116-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 162,
    "label": "rst-do-122-sm",
    "parentId": 150,
    "name": "Ръст до 122 см.",
    "slug": "rst-do-122-sm",
    "position": 12,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 12,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/rst-do-122-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 164,
    "label": "rst-do-128-sm",
    "parentId": 150,
    "name": "Ръст до 128 см.",
    "slug": "rst-do-128-sm",
    "position": 13,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 13,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/rst-do-128-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 165,
    "label": "rst-do-134-sm",
    "parentId": 150,
    "name": "Ръст до 134  см.",
    "slug": "rst-do-134-sm",
    "position": 14,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 14,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/rst-do-134-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 166,
    "label": "rst-do-140-sm",
    "parentId": 150,
    "name": "Ръст до 140 см.",
    "slug": "rst-do-140-sm",
    "position": 15,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 15,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/rst-do-140-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 167,
    "label": "rst-do-146-sm",
    "parentId": 150,
    "name": "Ръст до 146 см.",
    "slug": "rst-do-146-sm",
    "position": 16,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 16,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/rst-do-146-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 168,
    "label": "rst-do-152-sm",
    "parentId": 150,
    "name": "Ръст до 152 см.",
    "slug": "rst-do-152-sm",
    "position": 17,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 17,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/rst-do-152-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 169,
    "label": "rst-do-158-sm",
    "parentId": 150,
    "name": "Ръст до 158 см.",
    "slug": "rst-do-158-sm",
    "position": 18,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 18,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/rst-do-158-sm/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 170,
    "label": "shapki-shalove-drugi-aksesoari",
    "parentId": 150,
    "name": "Шапки, шалове, други аксесоари",
    "slug": "shapki-shalove-drugi-aksesoari",
    "position": 4,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 4,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/drehi/shapki-shalove-drugi-aksesoari/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 171,
    "label": "spalno-belo-zavivki-i-chuvali",
    "parentId": 178,
    "name": "Спално бельо, завивки и чували",
    "slug": "spalno-belo-zavivki-i-chuvali",
    "position": 3,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 3,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/mebeli-za-detskata-staya-tekstil/spalno-belo-zavivki-i-chuvali/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 173,
    "label": "obuvki",
    "parentId": 139,
    "name": "Обувки",
    "slug": "obuvki",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 2,
    "children": [
      174,
      175,
      176,
      177,
      351
    ],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/obuvki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 174,
    "label": "otvoreni-obuvki",
    "parentId": 173,
    "name": "Отворени обувки",
    "slug": "otvoreni-obuvki",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 1,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/obuvki/otvoreni-obuvki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 175,
    "label": "zatvoreni-obuvki",
    "parentId": 173,
    "name": "Затворени обувки",
    "slug": "zatvoreni-obuvki",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 2,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/obuvki/zatvoreni-obuvki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 176,
    "label": "boti-i-botushi",
    "parentId": 173,
    "name": "Боти и ботуши",
    "slug": "boti-i-botushi",
    "position": 3,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 3,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/obuvki/boti-i-botushi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 177,
    "label": "buyki-pantofi-toplinki-i-terlichki",
    "parentId": 173,
    "name": "Буйки, пантофи, топлинки и терлички",
    "slug": "buyki-pantofi-toplinki-i-terlichki",
    "position": 4,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 4,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/obuvki/buyki-pantofi-toplinki-i-terlichki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 178,
    "label": "mebeli-za-detskata-staya-tekstil",
    "parentId": 139,
    "name": "Мебели за детската стая, текстил",
    "slug": "mebeli-za-detskata-staya-tekstil",
    "position": 5,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 5,
    "children": [
      171,
      181,
      182,
      183
    ],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/mebeli-za-detskata-staya-tekstil/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 179,
    "label": "prohodilki",
    "parentId": 195,
    "name": "Проходилки",
    "slug": "prohodilki",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 1,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/prohodilki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 180,
    "label": "shezlongi-lyulki",
    "parentId": 195,
    "name": "Шезлонги, люлки",
    "slug": "shezlongi-lyulki",
    "position": 4,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 4,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/shezlongi-lyulki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 181,
    "label": "kosharki",
    "parentId": 178,
    "name": "Кошарки",
    "slug": "kosharki",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 1,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/mebeli-za-detskata-staya-tekstil/kosharki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 182,
    "label": "legla-garderobi-matratsi",
    "parentId": 178,
    "name": "Легла, гaрдероби, матраци",
    "slug": "legla-garderobi-matratsi",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 2,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/mebeli-za-detskata-staya-tekstil/legla-garderobi-matratsi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 183,
    "label": "drugi",
    "parentId": 178,
    "name": "Други",
    "slug": "drugi",
    "position": 4,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 4,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/mebeli-za-detskata-staya-tekstil/drugi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 185,
    "label": "bebeshki-i-detski-kolichki",
    "parentId": 139,
    "name": "Бебешки и детски колички",
    "slug": "bebeshki-i-detski-kolichki",
    "position": 3,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 3,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/bebeshki-i-detski-kolichki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 187,
    "label": "kengura-ranichki-i-kaishki",
    "parentId": 195,
    "name": "Кенгура, ранички и каишки",
    "slug": "kengura-ranichki-i-kaishki",
    "position": 8,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 8,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/kengura-ranichki-i-kaishki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 191,
    "label": "vanichki-i-komplekti-za-kpane",
    "parentId": 195,
    "name": "Ванички и комплекти за къпане",
    "slug": "vanichki-i-komplekti-za-kpane",
    "position": 5,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 5,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/vanichki-i-komplekti-za-kpane/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 192,
    "label": "havliyki-i-halati",
    "parentId": 195,
    "name": "Хавлийки и халати",
    "slug": "havliyki-i-halati",
    "position": 6,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 6,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/havliyki-i-halati/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 195,
    "label": "aksesoari",
    "parentId": 139,
    "name": "Аксесоари",
    "slug": "aksesoari",
    "position": 6,
    "viewType": "list",
    "iconName": "",
    "level": 2,
    "displayOrder": 6,
    "children": [
      132,
      179,
      180,
      187,
      191,
      192,
      196,
      197,
      198,
      199,
      200,
      202,
      203
    ],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 196,
    "label": "bebefoni",
    "parentId": 195,
    "name": "Бебефони",
    "slug": "bebefoni",
    "position": 3,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 3,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/bebefoni/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 197,
    "label": "ovlazhniteli-i-yonizatori-na-vzduh",
    "parentId": 195,
    "name": "Овлажнители и йонизатори на въздух",
    "slug": "ovlazhniteli-i-yonizatori-na-vzduh",
    "position": 7,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 7,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/ovlazhniteli-i-yonizatori-na-vzduh/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 198,
    "label": "aksesoari-za-krmachki",
    "parentId": 195,
    "name": "Аксесоари за кърмачки",
    "slug": "aksesoari-za-krmachki",
    "position": 9,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 9,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/aksesoari-za-krmachki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 199,
    "label": "pompi-za-krma",
    "parentId": 195,
    "name": "Помпи за кърма",
    "slug": "pompi-za-krma",
    "position": 10,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 10,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/pompi-za-krma/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 200,
    "label": "sdove-pribori-shisheta-biberoni",
    "parentId": 195,
    "name": "Съдове, прибори, шишета, биберони",
    "slug": "sdove-pribori-shisheta-biberoni",
    "position": 11,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 11,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/sdove-pribori-shisheta-biberoni/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 202,
    "label": "peleni-pampersi",
    "parentId": 195,
    "name": "Пелени, памперси",
    "slug": "peleni-pampersi",
    "position": 13,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 13,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/peleni-pampersi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 203,
    "label": "higienni-preparati-sterilizatori",
    "parentId": 195,
    "name": "Хигиенни препарати, стерилизатори",
    "slug": "higienni-preparati-sterilizatori",
    "position": 12,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 12,
    "children": [],
    "path": "https://www.olx.bg/za-bebeto-i-deteto/aksesoari/higienni-preparati-sterilizatori/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 207,
    "label": "damski-drehi",
    "parentId": 656,
    "name": "Дамски дрехи",
    "slug": "damski-drehi",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 1,
    "children": [
      129,
      208,
      209,
      210,
      211,
      212,
      213,
      214,
      215,
      216,
      217,
      218,
      219,
      220,
      221,
      222,
      223,
      224,
      225,
      226,
      227,
      982,
      984
    ],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 208,
    "label": "poli",
    "parentId": 207,
    "name": "Поли",
    "slug": "poli",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 1,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/poli/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 209,
    "label": "rokli-i-sukmani",
    "parentId": 207,
    "name": "Рокли и сукмани",
    "slug": "rokli-i-sukmani",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 2,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/rokli-i-sukmani/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 210,
    "label": "dnki",
    "parentId": 207,
    "name": "Дънки",
    "slug": "dnki",
    "position": 3,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 3,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/dnki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 211,
    "label": "pantaloni-i-bermudi",
    "parentId": 207,
    "name": "Панталони и бермуди",
    "slug": "pantaloni-i-bermudi",
    "position": 4,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 4,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/pantaloni-i-bermudi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 212,
    "label": "sportni-ekipi-i-klinove",
    "parentId": 207,
    "name": "Спортни екипи, суичъри, клинове",
    "slug": "sportni-ekipi-i-klinove",
    "position": 5,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 5,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/sportni-ekipi-i-klinove/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 213,
    "label": "kostyumi",
    "parentId": 207,
    "name": "Костюми",
    "slug": "kostyumi",
    "position": 6,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 6,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/kostyumi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 214,
    "label": "rizi",
    "parentId": 207,
    "name": "Ризи",
    "slug": "rizi",
    "position": 7,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 7,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/rizi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 215,
    "label": "zhiletki-eletsi-rakavi",
    "parentId": 207,
    "name": "Жилетки, елеци, ръкави",
    "slug": "zhiletki-eletsi-rakavi",
    "position": 8,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 8,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/zhiletki-eletsi-rakavi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 216,
    "label": "tuniki",
    "parentId": 207,
    "name": "Туники",
    "slug": "tuniki",
    "position": 9,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 9,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/tuniki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 217,
    "label": "teniski",
    "parentId": 207,
    "name": "Тениски",
    "slug": "teniski",
    "position": 10,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 10,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/teniski/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 218,
    "label": "potnitsi",
    "parentId": 207,
    "name": "Потници",
    "slug": "potnitsi",
    "position": 11,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 11,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/potnitsi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 219,
    "label": "korseti-byustieta",
    "parentId": 207,
    "name": "Корсети, бюстиета",
    "slug": "korseti-byustieta",
    "position": 12,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 12,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/korseti-byustieta/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 220,
    "label": "bluzi-s-dlg-rkav-puloveri-suichri",
    "parentId": 207,
    "name": "Блузи с дълъг ръкав и пуловери",
    "slug": "bluzi-s-dlg-rkav-puloveri-suichri",
    "position": 13,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 13,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/bluzi-s-dlg-rkav-puloveri-suichri/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 221,
    "label": "saka-i-yaketa",
    "parentId": 207,
    "name": "Сака и якета",
    "slug": "saka-i-yaketa",
    "position": 14,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 14,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/saka-i-yaketa/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 222,
    "label": "palta-trenchkoti-manta",
    "parentId": 207,
    "name": "Палта, тренчкоти, манта",
    "slug": "palta-trenchkoti-manta",
    "position": 15,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 15,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/palta-trenchkoti-manta/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 223,
    "label": "noschnitsi-i-pizhami",
    "parentId": 207,
    "name": "Нощници и пижами",
    "slug": "noschnitsi-i-pizhami",
    "position": 17,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 17,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/noschnitsi-i-pizhami/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 224,
    "label": "banski-kostyumi",
    "parentId": 207,
    "name": "Бански костюми",
    "slug": "banski-kostyumi",
    "position": 18,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 18,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/banski-kostyumi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 225,
    "label": "komplekti",
    "parentId": 207,
    "name": "Комплекти",
    "slug": "komplekti",
    "position": 19,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 19,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/komplekti/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 226,
    "label": "belo",
    "parentId": 207,
    "name": "Бельо",
    "slug": "belo",
    "position": 20,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 20,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/belo/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 227,
    "label": "drugi",
    "parentId": 207,
    "name": "Други",
    "slug": "drugi",
    "position": 23,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 23,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/damski-drehi/drugi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 228,
    "label": "damski-obuvki",
    "parentId": 657,
    "name": "Дамски обувки",
    "slug": "damski-obuvki",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 1,
    "children": [
      229,
      230,
      231,
      232,
      233
    ],
    "path": "https://www.olx.bg/moda/obuvki/damski-obuvki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 229,
    "label": "zimni-obuvki-boti-botushi",
    "parentId": 228,
    "name": "Зимни обувки, боти, ботуши",
    "slug": "zimni-obuvki-boti-botushi",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 2,
    "children": [],
    "path": "https://www.olx.bg/moda/obuvki/damski-obuvki/zimni-obuvki-boti-botushi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 230,
    "label": "proletni-esenni",
    "parentId": 228,
    "name": "Пролетни, есенни",
    "slug": "proletni-esenni",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 1,
    "children": [],
    "path": "https://www.olx.bg/moda/obuvki/damski-obuvki/proletni-esenni/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 231,
    "label": "letni-obuvki",
    "parentId": 228,
    "name": "Летни обувки",
    "slug": "letni-obuvki",
    "position": 3,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 3,
    "children": [],
    "path": "https://www.olx.bg/moda/obuvki/damski-obuvki/letni-obuvki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 232,
    "label": "sportni-obuvki-maratonki-ketsove",
    "parentId": 228,
    "name": "Спортни обувки, маратонки, кецове",
    "slug": "sportni-obuvki-maratonki-ketsove",
    "position": 4,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 4,
    "children": [],
    "path": "https://www.olx.bg/moda/obuvki/damski-obuvki/sportni-obuvki-maratonki-ketsove/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 233,
    "label": "drugi",
    "parentId": 228,
    "name": "Други",
    "slug": "drugi",
    "position": 5,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 5,
    "children": [],
    "path": "https://www.olx.bg/moda/obuvki/damski-obuvki/drugi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 234,
    "label": "mzhki-drehi",
    "parentId": 656,
    "name": "Мъжки дрехи",
    "slug": "mzhki-drehi",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 3,
    "displayOrder": 2,
    "children": [
      138,
      235,
      236,
      237,
      238,
      239,
      240,
      241,
      242,
      243,
      244,
      986,
      988
    ],
    "path": "https://www.olx.bg/moda/drehi/mzhki-drehi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 235,
    "label": "pantaloni",
    "parentId": 234,
    "name": "Панталони",
    "slug": "pantaloni",
    "position": 1,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 1,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/mzhki-drehi/pantaloni/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 236,
    "label": "dnki",
    "parentId": 234,
    "name": "Дънки",
    "slug": "dnki",
    "position": 2,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 2,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/mzhki-drehi/dnki/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 237,
    "label": "kostyumi-i-saka",
    "parentId": 234,
    "name": "Костюми и сака",
    "slug": "kostyumi-i-saka",
    "position": 4,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 4,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/mzhki-drehi/kostyumi-i-saka/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 238,
    "label": "rizi",
    "parentId": 234,
    "name": "Ризи",
    "slug": "rizi",
    "position": 3,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 3,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/mzhki-drehi/rizi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 239,
    "label": "puloveri-i-suichri",
    "parentId": 234,
    "name": "Пуловери и суичъри",
    "slug": "puloveri-i-suichri",
    "position": 5,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 5,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/mzhki-drehi/puloveri-i-suichri/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 240,
    "label": "flaneli-i-bluzi",
    "parentId": 234,
    "name": "Фланели и блузи",
    "slug": "flaneli-i-bluzi",
    "position": 6,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 6,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/mzhki-drehi/flaneli-i-bluzi/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  },
  {
    "id": 241,
    "label": "yaketa-i-palta",
    "parentId": 234,
    "name": "Якета и палта",
    "slug": "yaketa-i-palta",
    "position": 8,
    "viewType": "list",
    "iconName": "",
    "level": 4,
    "displayOrder": 8,
    "children": [],
    "path": "https://www.olx.bg/moda/drehi/mzhki-drehi/yaketa-i-palta/?search%5Border%5D=created_at:desc",
    "type": "goods",
    "isAdding": true,
    "isSearch": false,
    "isOfferSeek": false,
    "privateBusiness": true,
    "photosMax": 12
  }
]
