import type { AppConfig } from "@/types/config";

export const sequenceConfig: AppConfig = {
  globalSettings: {
    defaultScrollMultiplier: 150,
    theme: "dark",
  },
  sequences: [
    {
      id: "main-sequence1",
      framePrefix: "orange_",
      totalFrames: 93,
      frameExtension: "jpg",
      title: "Пътят към Здравето",
      description: "Открийте балансирана нутрициология за по-добър живот",
      scrollMultiplier: 300,
      totalSlides: 6,
      preloadAhead: 15,
      showDevInfo: false,
      overlayClassName: "bg-black/50",
      textSlides: [
        {
          id: "slide-1-1",
          text: "HARMONY ПРОГРАМА\nТвоят път към здравето и лекотата",
          slideIndex: 0,
          position: "center",
          style: "heading",
          imageUrl: "/logo.png",
        },
        {
          id: "slide-1-2",
          text: "Harmony Програм е персонализирана програма за хранене, която започва с анализ на коса, за да разкрие кои храни възпаляват твоето тяло.",
          slideIndex: 1,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-1-3",
          text: "Изследваме 180 храни и ти даваме: списък с индивидуално неподходящи храни.",
          slideIndex: 2,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-1-4",
          text: "...насоки как да ги изключиш и кога да ги върнеш...",
          slideIndex: 3,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-1-5",
          text: "...план за постигане на баланс, без глад и лишения.",
          slideIndex: 4,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-1-6",
          text: "Важно: Програмата не е за цял живот — достатъчни са няколко седмици, за да видиш първите резултати!",
          slideIndex: 5,
          position: "center",
          style: "heading",
        },
      ],
    },
    {
      id: "main-sequence2",
      framePrefix: "rice_",
      totalFrames: 156,
      frameExtension: "jpg",
      title: "Пътят към Здравето",
      description: "Открийте балансирана нутрициология за по-добър живот",
      scrollMultiplier: 300,
      totalSlides: 6,
      preloadAhead: 15,
      showDevInfo: false,
      overlayClassName: "bg-black/50",
      textSlides: [
        {
          id: "slide-2-1",
          text: "Защо другите диети не работят?",
          slideIndex: 0,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-2-2",
          text: "Другите диети са универсални — броят калории, но не отчитат: твоя метаболизъм.",
          slideIndex: 1,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-2-3",
          text: "...твоите възпалителни реакции...",
          slideIndex: 2,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-2-4",
          text: "...твоите индивидуални нужди.",
          slideIndex: 3,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-2-5",
          text: "Дори “здравословни” храни като краставица, домат или авокадо могат да вредят, ако тялото ти ги възприема като дразнител.",
          slideIndex: 4,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-2-6",
          text: "Защо анализ от коса? Косъмът е носител на твоята ДНК информация.",
          slideIndex: 5,
          position: "center",
          style: "heading",
        },
      ],
    },
    {
      id: "main-sequence3",
      framePrefix: "fit_",
      totalFrames: 156,
      frameExtension: "jpg",
      title: "Пътят към Здравето",
      description: "Открийте балансирана нутрициология за по-добър живот",
      scrollMultiplier: 300,
      totalSlides: 6,
      preloadAhead: 15,
      showDevInfo: false,
      overlayClassName: "bg-black/50",
      textSlides: [
        {
          id: "slide-3-1",
          text: "Какво печелиш?",
          slideIndex: 0,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-3-2",
          text: "Когато махнем възпалителните храни, тялото започва да: гори мазнини.",
          slideIndex: 1,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-3-3",
          text: "...отпуска натрупаните течности...",
          slideIndex: 2,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-3-4",
          text: "...облекчава ставите...",
          slideIndex: 3,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-3-5",
          text: "...възстановява енергията.",
          slideIndex: 4,
          position: "center",
          style: "heading",
        },
        {
          id: "slide-3-6",
          text: "Подарък за теб! Книжка с 1 седмица примерно меню, за да започнеш уверено и лесно.",
          slideIndex: 5,
          position: "center",
          style: "heading",
        },
      ],
    },
    {
      id: "static-content",
      type: "static",
      title: "Как да започнеш?",
      description: "Промени живота си още днес!",
      framePrefix: "",
      totalFrames: 0,
      frameExtension: "",
      scrollMultiplier: 0,
      totalSlides: 0,
      textSlides: [
        {
          id: "static-1",
          text: "Обади се на 089 8800456",
        },
        {
          id: "static-2",
          text: "Заяви своя персонален тест",
        },
        {
          id: "static-3",
          text: "Вземи своя план и подарък меню",
        },
        {
          id: "static-4",
          text: "https://dietologix.com",
        },
      ],
    },
  ],
};